### ISSUE TITLE
Add way to check to see if a user can access a route?

### ISSUE THREAD

**Issue by MyklClason** [enjaku4/rabarber#28]
Seems pretty useful. Something like this:

```
link_to "Users", users_path if user.can_access_path?(users_path)
```

 For this purpose, it just needs to check if the path without params is accessible to the user or not.

**Comment by enjaku4** [comment]
I considered this too. But, after looking into it, I don't think it's possible to implement because of the dynamic rules.

The thing is, the logic inside dynamic rules, for example, `grant_access action: :foo, roles: :bar, if: -> { params[:foo] == "bar" }` or `unless: -> { current_user.banned? }`, can be pretty much anything. And since these blocks can only be evaluated at the request time, there's no way to know beforehand if a user has access.

I'm closing this issue, but if you have any ideas feel free to open a PR.

**Comment by MyklClason** [comment]
True, but it seems like dynamic rules are optional, unlike most other authorization systems where dynamic rules are required for it to work. Hence, I'm not even sure this needs dynamic rules, though even with them it still seems like there is a way around the issue. It just depends on how hard one leans on "role-based".

1. I'm curious on an example usage of  `if: -> { params[:foo] == "bar" }`. My impression is that it's a bad idea. It looks like you are basically allowing someone to have a role based on a parameter, a parameter that the user could have set themselves. I could see a temporary role as a viable option. However, in that case, it seems like it could be handled better. IE: `grant_access action: :foo, roles: [:zee, :bar], allows_temp_role: {foo: [:bar]}` to allow the `foo` param to set the `bar` role but not the `zee` role.
2. User.assign_role(:banned) seems workable, though there are a few reasons for why it is probably not ideal, though I can also think of some solutions to work around that issue.
3. Even if we ignore the above and keep the dynamic rules, the `user.can_access_path?(users_path)` implies that `user` could be the `current_user` and we can run the check as-is with just some logic to set the user as the current user. In the worst case, we might need to allow the user to pass some other parameters to handle missing data. IE: `can_access_path?(users_path, current_user: user)`. This may not work in all cases, but it may work often enough for it to be worth doing.

Another option might be to allow the app to disable dynamic rules and then allow for additional functionality that is only possible while dynamic rules are disabled. However, as mentioned in #30, if the rules were exposed as an official API, allowing other devs to handle this logic would be possible. Technically it is exposed, but not officially; some official documentation on how the rules can be checked externally would be useful.

**Comment by enjaku4** [comment]
The examples of dynamic rules I provided were not real and intended only to illustrate that literally anything can be inside the block.

Disabling dynamic rules and allowing additional functionality based on them seems very difficult to both implement and use.

As for your proposal to completely abandon dynamic rules, it is actually interesting. It seems that any dynamic rule can be handled either by adding an additional role, or it can be part of business logic that can be implemented beyond the authorization logic. Removing dynamic rules would also open the way for new features like `can_access_path?` method you suggested.

Although, at this time we have no plans to deviate from our current development plans, but I will add this idea to the backlog to consider later.
