### ISSUE TITLE
A simple role based model scoping approach

### ISSUE THREAD

**Issue by MyklClason** [enjaku4/rabarber#29]
Implemented quick model scoping and figured I'd share. Allows you to provide a list of roles for which access is permitted. The first role listed with access will be the scope used. If there is no scope for that role, they get `Model.none`.

In `ApplicationController`, add helper method for scope access.

```
  def scope_access(model_class, *roles)
    model_class.send(:grant_scope, current_user, *roles)
  end
```

In `ApplicationRecord`

```
  def self.grant_scope(user, *role_syms)
    role_syms.each do |role_sym|
      return send(:"#{role_sym}_access", user) if user.role_sym == role_sym
    end

    none
  end
```

In model

```
  scope :admin_access, ->(user) { all }
  scope :user_access, ->(user) { all.where(user_id: user.id) }
```

Usage in a controller:

```
scope_access(Model, :admin, :user).find(params[:id])
```

**Comment by enjaku4** [comment]
Thank you for the proposal. However, our focus with Rabarber is on role-based access control without handling data scoping. 

We see scoping as a part of the business logic layer, and its implementation can vary considerably depending on the specific requirements of each application. Moreover, scoping is not necessarily dependent on user alone and can be implemented easily without use of any additional libraries. Given this, we currently have no plans to include data scoping in Rabarber.
