### ISSUE TITLE
Perhaps expose the permissions in a easy to process format?

### ISSUE THREAD

**Issue by MyklClason** [enjaku4/rabarber#30]
Specifically:

https://github.com/enjaku4/rabarber/blob/main/lib/rabarber/permissions.rb

The controller_rules and action_rules would be rather nice to be able to easily process and could make it easier for other devs to build onto this. IE: the `can_access_path(users_path)` one I posted earlier would be easier to implement without a PR if it was easier to quickly grab the permissions. Right now, it seems like it could be done, but as more of an unofficial API usage.

**Comment by enjaku4** [comment]
Thanks for your suggestion. We're considering a method like `can_access_path?`, it's not currently a top priority though. 

As for exposing permissions, your suggestion is a bit too abstract. If you have a specific API in mind, feel free to open a pull request with your proposal.
