### ISSUE TITLE
Rabarber initialiser

### ISSUE THREAD

**Issue by benbagley** [enjaku4/rabarber#40]
Hi, I've started playing about with this gem and might be a silly question but what do we put here?

```ruby
Rabarber.configure do |config|
...
  config.when_actions_missing = -> (missing_actions, context) { ... }
  config.when_roles_missing = -> (missing_roles, context) { ... }
  config.when_unauthorized = -> (controller) { ... }
end
```

Here is what I have:

```ruby
 Rabarber.configure do |config|
  config.cache_enabled = true
  config.current_user_method = :current_user
  config.must_have_roles = false

  config.when_actions_missing = -> (missing_actions, context) do
    raise ActionController::RoutingError.new('Not Found')
  end

  config.when_roles_missing = -> (missing_roles, context) do
    redirect_to root_path, alert: 'You do not have sufficient permissions'
  end

  config.when_unauthorized = -> (controller) do
    redirect_to root_path, alert: 'You are not authorized to access this page'
  end
end
```

But I'm getting
```
undefined local variable or method `root_path' for main:Object
```

Any help here would be great.

**Comment by enjaku4** [comment]
Hi there,

I'd like to address a couple of points regarding the issue you raised:

1. As stated in our [contributing guidelines](https://github.com/enjaku4/rabarber/blob/main/CONTRIBUTING.md), issues are meant for reporting bugs. If you have questions or need assistance with using the gem, we encourage you to use the Discussions section.
2. The [README](https://github.com/enjaku4/rabarber?tab=readme-ov-file#configuration) file provides comprehensive guidance on how to configure and use the gem. However, if you find any areas lacking clarity or have suggestions for improvements, we welcome your contributions through pull requests.
3. Regarding the error with the `root_path` method, there is no such method in the specific context of that lambda. Only the controller instance (`controller` argument) is available within the lambda, so you have to derive everything you need from it. You're also welcome to take a look the implementation of the default logic; you can find it [here](https://github.com/enjaku4/rabarber/blob/main/lib/rabarber/configuration.rb#L71-L94). Probably, it will help you understand what you can possibly have inside your lambdas.

I hope this clarifies the situation for you. I'm closing the issue as it is more suited for discussions.
